version: "3.7"

services:
  app:
    image: rust:1.43
#    command: sh -c "cargo install --path . && /usr/local/cargo/bin/bitcoin_trend"
    command: sh -c "cargo build --release && /app/target/release/bitcoin_trend --workingdir=/app/data"
    ports:
      - 4000:80
    working_dir: /app
    volumes:
      - ./:/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    restart: always
    volumes:
      - bitcoin-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: j23f24hgf359bgfu4gf4o0i34nf0oi4g
      MYSQL_DATABASE: bitcoin_trend

volumes:
  bitcoin-mysql-data: